- Cargo.lock
- Makefile
- runtime/Cargo.toml
- runtime/src/lib.rs
- src/chain_spec.rs
> Add operator collective

- Cargo.lock
- modules/primitives/src/lib.rs
- modules/traits/Cargo.toml
- modules/traits/src/lib.rs
* Update liquidity pool trait for #12 
* Update orml
* Fix warning
> Update liquidity pool trait

- Cargo.lock
- modules/primitives/src/lib.rs
- modules/synthetic-protocol/Cargo.toml
- modules/synthetic-protocol/src/lib.rs
- modules/synthetic-protocol/src/mock.rs
- modules/synthetic-protocol/src/tests.rs
- runtime/src/lib.rs
* unit tests
* fixed calculations
* renaming
> Synthetic protocol unit tests

- modules/liquidity-pools/src/lib.rs
- modules/liquidity-pools/src/tests.rs
- modules/synthetic-protocol/src/lib.rs
- modules/synthetic-protocol/src/mock.rs
- modules/synthetic-protocol/src/tests.rs
- modules/traits/src/lib.rs
- runtime/src/lib.rs
Also refactored `LiquidityPools` trait.
> Allow other runtime modules withdraw liquidity from pool

- Makefile
- modules/primitives/src/lib.rs
- modules/synthetic-protocol/Cargo.toml
- modules/synthetic-protocol/src/lib.rs
- modules/synthetic-protocol/src/mock.rs
- modules/synthetic-protocol/src/tests.rs
- runtime/tests/integration_test.rs
Enabled trades wasn't check before and this fixes it.
Also some other refactors.
> Refactor and fix

- Cargo.lock
- modules/synthetic-protocol/src/lib.rs
- modules/synthetic-protocol/src/mock.rs
- modules/synthetic-tokens/Cargo.toml
- modules/synthetic-tokens/src/lib.rs
- modules/synthetic-tokens/src/mock.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- runtime/tests/integration_test.rs
> implement liquiditypool-manager can_remove

- modules/synthetic-protocol/src/mock.rs
- modules/synthetic-tokens/src/lib.rs
- modules/synthetic-tokens/src/mock.rs
- modules/synthetic-tokens/src/tests.rs
- runtime/src/lib.rs
> move synthetic-tokens constants in runtime

- modules/liquidity-pools/src/lib.rs
- modules/liquidity-pools/src/mock.rs
- modules/liquidity-pools/src/tests.rs
- modules/synthetic-protocol/src/lib.rs
- modules/synthetic-protocol/src/mock.rs
- modules/traits/src/lib.rs
- runtime/src/lib.rs
- runtime/tests/integration_test.rs
- src/chain_spec.rs
> add MinAdditionalCollateralRatio to liquidity pool

- modules/liquidity-pools/src/lib.rs
- modules/liquidity-pools/src/tests.rs
- modules/synthetic-protocol/src/mock.rs
- modules/synthetic-protocol/src/tests.rs
- runtime/tests/integration_test.rs
> modify synthetic-protocol withdraw-liquidity

- Cargo.lock
- modules/primitives/Cargo.toml
- modules/primitives/src/lib.rs
> implement manual encode/decode

- modules/primitives/src/lib.rs
- runtime/src/lib.rs
- runtime/tests/integration_test.rs
> update currencyld, add FBTC, FETH

- Cargo.lock
- Cargo.toml
> use jmalloc

- Cargo.lock
- Cargo.toml
- modules/margin-protocol/Cargo.toml
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- modules/primitives/Cargo.toml
- modules/primitives/src/arithmetic.rs
- modules/primitives/src/lib.rs
Will add unit tests in another PR.
> Margin Protocol Helper Methods

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/margin-protocol/src/tests.rs
With some minor fixes in helpers.
> Margin protocol: liquidity pool helpers unit tests

- Cargo.lock
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/margin-protocol/src/tests.rs
- modules/primitives/src/arithmetic.rs
- modules/synthetic-protocol/src/mock.rs
- modules/synthetic-protocol/src/tests.rs
- runtime/tests/integration_test.rs
> Open position

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/margin-protocol/src/tests.rs
> Close position

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/margin-protocol/src/tests.rs
> Deposit & withdraw

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/margin-protocol/src/tests.rs
> implement liquidity_pool_margin_call

- Cargo.lock
- modules/margin-liquidity-pools/Cargo.toml
- modules/margin-liquidity-pools/src/lib.rs
- modules/margin-liquidity-pools/src/mock.rs
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- modules/synthetic-liquidity-pools/src/mock.rs
- modules/synthetic-tokens/src/lib.rs
- modules/traits/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
* improve margin-protocol offchain worker
* move ensure_pool_safe_after_withdrawal into LiquidityPoolManager
Closes #117
> improve margin-protocol offchain worker

- modules/margin-liquidity-pools/src/mock.rs
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- modules/primitives/src/arithmetic.rs
- modules/synthetic-liquidity-pools/src/mock.rs
- modules/synthetic-tokens/src/lib.rs
- modules/traits/src/lib.rs
- runtime/Cargo.toml
> Liquidity pool manager

- Cargo.toml
- modules/margin-liquidity-pools/Cargo.toml
- modules/margin-protocol/Cargo.toml
- modules/primitives/Cargo.toml
- modules/synthetic-liquidity-pools/Cargo.toml
- modules/synthetic-protocol/Cargo.toml
- modules/synthetic-tokens/Cargo.toml
- modules/traits/Cargo.toml
- runtime/Cargo.toml
> update scale version 1.2.0

- modules/margin-protocol/src/tests.rs
* ensure transactions are submitted into the pool
> offchain_worker_improve_tests

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
Check free margin instead of margin level.
> Update open position

- features/margin.feature
- features/synthetic.feature
- runtime/src/lib.rs
- runtime/tests/margin_integration_test.rs
- runtime/tests/synthetic_integration_test.rs
> implement DataProvider for AUSD

- features/margin.feature
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/margin-protocol/src/tests.rs
- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
- tests/cucumber.rs
Non-positive `realizable` cannot happen in real life, but it's good to be handled as an edge case.
> Handle negative equity while closing position.

- Cargo.lock
- Cargo.toml
- modules/margin-protocol/rpc/Cargo.toml
- modules/margin-protocol/rpc/runtime-api/Cargo.toml
- modules/margin-protocol/rpc/runtime-api/src/lib.rs
- modules/margin-protocol/rpc/src/lib.rs
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/margin-protocol/src/tests.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- src/rpc.rs
> margin-protocol-rpc

- modules/margin-liquidity-pools/src/lib.rs
- modules/synthetic-liquidity-pools/src/lib.rs
- modules/synthetic-protocol/src/lib.rs
> add compact on balance type

- modules/synthetic-protocol/src/lib.rs
- modules/synthetic-protocol/src/mock.rs
- modules/synthetic-protocol/src/tests.rs
- runtime/src/tests.rs
> modify mint and redeem slippage logic in synthetic-protocol

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
> add position id to open position event

- modules/liquidity-pools/margin/src/lib.rs
- modules/liquidity-pools/margin/src/tests.rs
- runtime/tests/margin_integration_test.rs
> update set max spread

- Cargo.lock
- modules/margin-protocol/rpc/Cargo.toml
- modules/margin-protocol/rpc/runtime-api/Cargo.toml
- modules/margin-protocol/rpc/runtime-api/src/lib.rs
- modules/margin-protocol/rpc/src/lib.rs
- runtime/src/lib.rs
- src/rpc.rs
remove unneeded methods and unnecessary generics
> refactor margin rpc

- Cargo.lock
- modules/liquidity-pools/margin/src/lib.rs
- modules/liquidity-pools/margin/src/tests.rs
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- src/chain_spec.rs
See https://github.com/paritytech/substrate/issues/5620
And some other chain spec improvements
> Fix margin protocol issue

- Cargo.lock
- modules/liquidity-pools/margin/src/lib.rs
- modules/liquidity-pools/margin/src/tests.rs
- modules/liquidity-pools/synthetic/src/lib.rs
- modules/liquidity-pools/synthetic/src/tests.rs
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/margin-protocol/src/tests.rs
- modules/synthetic-protocol/src/lib.rs
- modules/synthetic-protocol/src/mock.rs
- modules/traits/src/lib.rs
- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
- runtime/tests/synthetic_integration_test.rs
- src/chain_spec.rs
- tests/cucumber.rs
* Ask/bid spread as `Balance`
* Max spread as `Balance`
Closes #189
> Change spread from Permill to Balance

- modules/margin-protocol/rpc/runtime-api/src/lib.rs
- modules/margin-protocol/rpc/src/lib.rs
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/margin-protocol/src/tests.rs
- runtime/src/lib.rs
- runtime/src/tests.rs
> Trader activities and profiles are per pool

- modules/primitives/src/lib.rs
- modules/synthetic-protocol/src/lib.rs
- modules/synthetic-protocol/src/mock.rs
- runtime/src/lib.rs
> Remove price <=> balance type converter.

- Cargo.lock
- Cargo.toml
- modules/synthetic-protocol/rpc/Cargo.toml
- modules/synthetic-protocol/rpc/runtime-api/Cargo.toml
- modules/synthetic-protocol/rpc/runtime-api/src/lib.rs
- modules/synthetic-protocol/rpc/src/lib.rs
- modules/synthetic-protocol/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- src/rpc.rs
> Synthetic protocol RPC.

- modules/liquidity-pools/base/src/mock.rs
- modules/liquidity-pools/margin/src/mock.rs
- modules/liquidity-pools/synthetic/src/mock.rs
- modules/margin-protocol/rpc/runtime-api/src/lib.rs
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- modules/synthetic-tokens/src/lib.rs
- modules/traits/src/lib.rs
- runtime/src/lib.rs
- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
> Refactor liquidity pools manager

- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
- tests/cucumber.rs
> add margin accumulate swap cases

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- runtime/src/lib.rs
> Valid transaction

- Cargo.lock
- Cargo.toml
- modules/liquidity-pools/margin/Cargo.toml
- modules/liquidity-pools/margin/src/lib.rs
- modules/liquidity-pools/synthetic/Cargo.toml
- modules/margin-protocol/rpc/runtime-api/Cargo.toml
- modules/margin-protocol/rpc/runtime-api/src/lib.rs
- modules/margin-protocol/src/lib.rs
- modules/primitives/src/arithmetic.rs
- modules/traits/Cargo.toml
- modules/traits/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
- src/chain_spec.rs
- tests/cucumber.rs
> replace Fixed128

- Cargo.lock
- runtime/Cargo.toml
- runtime/build.rs
@zjb0807 this should fix running benchmarking in wasm issue
> bump wasm builder version

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- runtime/tests/margin_integration_test.rs
Spread is Balance now, not Permill. So just add the value.
> _liquidity_pool_close_position spread profit and penalty

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- runtime/tests/margin_integration_test.rs
> fix liquidate a trader reset balance

- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
- tests/cucumber.rs
> add thresholds test

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- runtime/tests/margin_integration_test.rs
> fix accumulated swap rate

- runtime/src/lib.rs
https://github.com/paritytech/polkadot/pull/1086
> increase block hash count

- Cargo.lock
- Cargo.toml
- modules/margin-protocol/rpc/runtime-api/Cargo.toml
- modules/margin-protocol/rpc/runtime-api/src/lib.rs
- modules/synthetic-protocol/rpc/runtime-api/Cargo.toml
- modules/synthetic-protocol/rpc/runtime-api/src/lib.rs
- runtime/Cargo.toml
- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
- runtime/tests/synthetic_integration_test.rs
- tests/cucumber.rs
Depend on: https://github.com/laminar-protocol/cucumber-features/pull/12
> Add rpc test

- modules/primitives/src/lib.rs
- src/chain_spec.rs
> update currency pairs

- Cargo.lock
- modules/liquidity-pools/margin/Cargo.toml
- modules/liquidity-pools/margin/src/lib.rs
- modules/liquidity-pools/margin/src/mock.rs
- modules/liquidity-pools/margin/src/tests.rs
- modules/primitives/src/lib.rs
- runtime/src/lib.rs
- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
- src/chain_spec.rs
- tests/cucumber.rs
> Refactor swap accumulate

- modules/liquidity-pools/base/src/lib.rs
- modules/liquidity-pools/base/src/tests.rs
- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
- runtime/tests/synthetic_integration_test.rs
> Add transfer liquidity pool

- .github/workflows/test.yml
- runtime/src/benchmarking/margin_liquidity_pools.rs
- Run benchmarking tests in CI
- Fix broken tests.
> Benchmarking tests

- runtime/Cargo.toml
- runtime/build.rs
> Update wasm builder version 1.0.11

- Cargo.toml
> Compile some deps with opt-level=3 to make dev profile faster.

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- runtime/tests/margin_integration_test.rs
> Enp ell calculation optimization

- Cargo.lock
- Cargo.toml
- modules/liquidity-pools/base/src/lib.rs
- modules/liquidity-pools/base/src/tests.rs
- modules/liquidity-pools/margin/src/lib.rs
- modules/liquidity-pools/margin/src/mock.rs
- modules/liquidity-pools/margin/src/tests.rs
- modules/liquidity-pools/synthetic/src/mock.rs
- modules/liquidity-pools/synthetic/src/tests.rs
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- modules/primitives/src/lib.rs
- modules/synthetic-tokens/src/lib.rs
- modules/synthetic-tokens/src/tests.rs
- runtime/src/benchmarking/margin_protocol.rs
- runtime/src/tests.rs
- src/chain_spec.rs
> Storage optimization

- runtime/src/benchmarking/base_liquidity_pools.rs
- runtime/src/benchmarking/margin_protocol.rs
- runtime/src/benchmarking/mod.rs
- runtime/src/benchmarking/synthetic_protocol.rs
- runtime/src/lib.rs
The last piece of benchmarking.
> Base liquidity pools benchmarking

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/constants.rs
- runtime/src/lib.rs
> Set WeightToFee to WeightToFeePolymial.

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
> Implement repayment to pools on close position.

- modules/liquidity-pools/margin/src/lib.rs
- modules/liquidity-pools/margin/src/tests.rs
- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/traits/src/lib.rs
Also removed duplicated allowed leverage check.
Closes #272
> Detailed open position error

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- runtime/tests/margin_integration_test.rs
Force close position, `penalty = spread * held * 2`
> Fix force close position penalty

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
- runtime/src/benchmarking/margin_protocol.rs
> Replace 'Option<bool>' with 'Option<()>'.

- modules/margin-protocol/src/lib.rs
> Use offchain worker lock

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/mock.rs
- modules/traits/src/lib.rs
- runtime/src/lib.rs
- runtime/src/tests.rs
- runtime/tests/margin_integration_test.rs
> Update treasury in margin protocol.

- modules/margin-protocol/src/lib.rs
- modules/margin-protocol/src/tests.rs
> Trader's risk threshold should be per pool.

- modules/margin-protocol/src/lib.rs
> Avoid sort_unstable_by.

- README.md
I was attempting to build the project, but it kept giving me various errors.
Turns out I didn't have `llvm` and `clang` installed. I've added these instructions in the PR to hopefully make life easier for future builders!
> Update README.md to include prerequisites.
